Adding the task_status_change() method fro the example
While doing the ToDo Tutorial, I got this issue: `AttributeError: 'Listado' object has no attribute 'task_status_change'`. It seems we were missing the `task_status_change`method, so I added it just for clarify in the docs, I've also added it to the `add_clicked()` method too.

Again, thanks for your work guys!